# Generated by Django 5.0.3 on 2024-05-20 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kompaniya',
                'verbose_name_plural': 'Kompaniyalar',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('comfort', models.TextField(verbose_name='qulaylik')),
                ('about', models.TextField(verbose_name='haqida')),
                ('time', models.DateTimeField(verbose_name='Uchish vaqti')),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.category', verbose_name='Kategoriya')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': 'Bilet',
                'verbose_name_plural': 'Biletlar',
            },
        ),
    ]
